### ISSUE TITLE
FileUtil does not exist in the current context

### ISSUE THREAD

**Issue by LuckyDucky-creator** [EPPlusSoftware/EPPlus.Samples.CSharp#2]
Hello! In your documentation, in the first file (create a simple workbook) in the code (Getting Started Sample) on line 116:
var xlFile = FileUtil.GetCleanFileInfo("1.01-GettingStarted.xlsx");
The compiler throws an error: the FileUtil name does not exist in the current context. Do I need to use another class?

**Comment by JanKallman** [comment]
Hello,
Do you open the solution, [EPPlus.Sample](https://github.com/EPPlusSoftware/EPPlus.Samples.CSharp/blob/master/EPPlus.Samples.CSharp.sln) in Visual Studio 2022?
